//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume cont.
        /// </summary>
        public static string Account_AccountName {
            get {
                return ResourceManager.GetString("Account_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Account_Address {
            get {
                return ResourceManager.GetString("Account_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista posturi.
        /// </summary>
        public static string Account_Button_AccountStreamStationList {
            get {
                return ResourceManager.GetString("Account_Button_AccountStreamStationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport perioada.
        /// </summary>
        public static string Account_Button_AccountTimeReport {
            get {
                return ResourceManager.GetString("Account_Button_AccountTimeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista melodii.
        /// </summary>
        public static string Account_Button_AccountTrackList {
            get {
                return ResourceManager.GetString("Account_Button_AccountTrackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amprenteaza.
        /// </summary>
        public static string Account_Button_CreateFingerprints {
            get {
                return ResourceManager.GetString("Account_Button_CreateFingerprints", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Account_Button_Dashboard {
            get {
                return ResourceManager.GetString("Account_Button_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume.
        /// </summary>
        public static string Account_FullName {
            get {
                return ResourceManager.GetString("Account_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id cont.
        /// </summary>
        public static string Account_Id {
            get {
                return ResourceManager.GetString("Account_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este activ.
        /// </summary>
        public static string Account_IsActive {
            get {
                return ResourceManager.GetString("Account_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Account_Phone {
            get {
                return ResourceManager.GetString("Account_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contul a fost creat cu succes!.
        /// </summary>
        public static string Account_SuccessfullyCreated {
            get {
                return ResourceManager.GetString("Account_SuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contul a fost actualizat cu succes!.
        /// </summary>
        public static string Account_SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("Account_SuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista conturi.
        /// </summary>
        public static string Account_Title_AccountList {
            get {
                return ResourceManager.GetString("Account_Title_AccountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creeaza cont.
        /// </summary>
        public static string Account_Title_CreateAccount {
            get {
                return ResourceManager.GetString("Account_Title_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica cont.
        /// </summary>
        public static string Account_Title_EditAccount {
            get {
                return ResourceManager.GetString("Account_Title_EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id cont.
        /// </summary>
        public static string ApplicationSetting_AccountId {
            get {
                return ResourceManager.GetString("ApplicationSetting_AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cont.
        /// </summary>
        public static string ApplicationSetting_AccountName {
            get {
                return ResourceManager.GetString("ApplicationSetting_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriere.
        /// </summary>
        public static string ApplicationSetting_Description {
            get {
                return ResourceManager.GetString("ApplicationSetting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id setare.
        /// </summary>
        public static string ApplicationSetting_Id {
            get {
                return ResourceManager.GetString("ApplicationSetting_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este activa.
        /// </summary>
        public static string ApplicationSetting_IsActive {
            get {
                return ResourceManager.GetString("ApplicationSetting_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denumire cheie.
        /// </summary>
        public static string ApplicationSetting_KeyName {
            get {
                return ResourceManager.GetString("ApplicationSetting_KeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valoare cheie.
        /// </summary>
        public static string ApplicationSetting_KeyValue {
            get {
                return ResourceManager.GetString("ApplicationSetting_KeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setarea a fost creata cu succes!.
        /// </summary>
        public static string ApplicationSetting_SuccessfullyCreated {
            get {
                return ResourceManager.GetString("ApplicationSetting_SuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setarea a fost actualizata cu succes!.
        /// </summary>
        public static string ApplicationSetting_SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("ApplicationSetting_SuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista setari.
        /// </summary>
        public static string ApplicationSetting_Title_ApplicationSettingList {
            get {
                return ResourceManager.GetString("ApplicationSetting_Title_ApplicationSettingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creeaza setarea.
        /// </summary>
        public static string ApplicationSetting_Title_CreateApplicationSetting {
            get {
                return ResourceManager.GetString("ApplicationSetting_Title_CreateApplicationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica setarea.
        /// </summary>
        public static string ApplicationSetting_Title_EditApplicationSetting {
            get {
                return ResourceManager.GetString("ApplicationSetting_Title_EditApplicationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La crearea amprentelor a aparut o eroare!.
        /// </summary>
        public static string CreateFingerprint_Error {
            get {
                return ResourceManager.GetString("CreateFingerprint_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amprentele au fost create cu succes!.
        /// </summary>
        public static string CreateFingerprint_Success {
            get {
                return ResourceManager.GetString("CreateFingerprint_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creeaza amprente.
        /// </summary>
        public static string CreateFingerprint_Title_FingerprintList {
            get {
                return ResourceManager.GetString("CreateFingerprint_Title_FingerprintList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status posturi.
        /// </summary>
        public static string Dashboard_Title_StreamStationStatusList {
            get {
                return ResourceManager.GetString("Dashboard_Title_StreamStationStatusList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Global_Button_Back {
            get {
                return ResourceManager.GetString("Global_Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ....
        /// </summary>
        public static string Global_Button_Browse {
            get {
                return ResourceManager.GetString("Global_Button_Browse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activeaza-le pe toate.
        /// </summary>
        public static string Global_Button_CheckAll {
            get {
                return ResourceManager.GetString("Global_Button_CheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Global_Button_Create {
            get {
                return ResourceManager.GetString("Global_Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amprenteaza.
        /// </summary>
        public static string Global_Button_CreateFingerprint {
            get {
                return ResourceManager.GetString("Global_Button_CreateFingerprint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Global_Button_Edit {
            get {
                return ResourceManager.GetString("Global_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Global_Button_Save {
            get {
                return ResourceManager.GetString("Global_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and continue.
        /// </summary>
        public static string Global_Button_SaveContinue {
            get {
                return ResourceManager.GetString("Global_Button_SaveContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debifeaza toate.
        /// </summary>
        public static string Global_Button_UncheckAll {
            get {
                return ResourceManager.GetString("Global_Button_UncheckAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toate.
        /// </summary>
        public static string Global_Lookup_All {
            get {
                return ResourceManager.GetString("Global_Lookup_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string Global_Lookup_IdZero {
            get {
                return ResourceManager.GetString("Global_Lookup_IdZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conturi.
        /// </summary>
        public static string Global_NavBar_Accounts {
            get {
                return ResourceManager.GetString("Global_NavBar_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setari.
        /// </summary>
        public static string Global_NavBar_ApplicationSettings {
            get {
                return ResourceManager.GetString("Global_NavBar_ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Global_NavBar_Dashboard {
            get {
                return ResourceManager.GetString("Global_NavBar_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Global_NavBar_Home {
            get {
                return ResourceManager.GetString("Global_NavBar_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapoarte.
        /// </summary>
        public static string Global_NavBar_Reports {
            get {
                return ResourceManager.GetString("Global_NavBar_Reports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport perioada.
        /// </summary>
        public static string Global_NavBar_Reports_Time {
            get {
                return ResourceManager.GetString("Global_NavBar_Reports_Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alocare posturi per cont.
        /// </summary>
        public static string Global_NavBar_StationAccountAllocation {
            get {
                return ResourceManager.GetString("Global_NavBar_StationAccountAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posturi.
        /// </summary>
        public static string Global_NavBar_StreamStations {
            get {
                return ResourceManager.GetString("Global_NavBar_StreamStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodii.
        /// </summary>
        public static string Global_NavBar_Tracks {
            get {
                return ResourceManager.GetString("Global_NavBar_Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raport perioada.
        /// </summary>
        public static string Reports_Title_TimeReport {
            get {
                return ResourceManager.GetString("Reports_Title_TimeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriere.
        /// </summary>
        public static string StreamStation_Description {
            get {
                return ResourceManager.GetString("StreamStation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id post.
        /// </summary>
        public static string StreamStation_Id {
            get {
                return ResourceManager.GetString("StreamStation_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este activ.
        /// </summary>
        public static string StreamStation_IsActive {
            get {
                return ResourceManager.GetString("StreamStation_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necesara conversie.
        /// </summary>
        public static string StreamStation_IsConvertionNeeded {
            get {
                return ResourceManager.GetString("StreamStation_IsConvertionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorul local.
        /// </summary>
        public static string StreamStation_LocalPath {
            get {
                return ResourceManager.GetString("StreamStation_LocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functioneaza.
        /// </summary>
        public static string StreamStation_Running {
            get {
                return ResourceManager.GetString("StreamStation_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denumire post.
        /// </summary>
        public static string StreamStation_StationName {
            get {
                return ResourceManager.GetString("StreamStation_StationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postul a fost creat cu succes!.
        /// </summary>
        public static string StreamStation_SuccessfullyCreated {
            get {
                return ResourceManager.GetString("StreamStation_SuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postul a fost actualizat cu succes!.
        /// </summary>
        public static string StreamStation_SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("StreamStation_SuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creaza post.
        /// </summary>
        public static string StreamStation_Title_CreateStreamStation {
            get {
                return ResourceManager.GetString("StreamStation_Title_CreateStreamStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica post.
        /// </summary>
        public static string StreamStation_Title_EditStreamStation {
            get {
                return ResourceManager.GetString("StreamStation_Title_EditStreamStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista posturi.
        /// </summary>
        public static string StreamStation_Title_StreamStationList {
            get {
                return ResourceManager.GetString("StreamStation_Title_StreamStationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorul unde se face transformarea.
        /// </summary>
        public static string StreamStation_TransformFolder {
            get {
                return ResourceManager.GetString("StreamStation_TransformFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string StreamStation_Url {
            get {
                return ResourceManager.GetString("StreamStation_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id cont.
        /// </summary>
        public static string TimeReport_AccountId {
            get {
                return ResourceManager.GetString("TimeReport_AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume cont.
        /// </summary>
        public static string TimeReport_AccountName {
            get {
                return ResourceManager.GetString("TimeReport_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procent cont.
        /// </summary>
        public static string TimeReport_AccountPercent {
            get {
                return ResourceManager.GetString("TimeReport_AccountPercent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rezultate cont.
        /// </summary>
        public static string TimeReport_AccountResultsInSeconds {
            get {
                return ResourceManager.GetString("TimeReport_AccountResultsInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conturi.
        /// </summary>
        public static string TimeReport_Accounts {
            get {
                return ResourceManager.GetString("TimeReport_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genereaza raport numar aparitii.
        /// </summary>
        public static string TimeReport_Button_GenerateReport_CountReportFirstAggregation {
            get {
                return ResourceManager.GetString("TimeReport_Button_GenerateReport_CountReportFirstAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genereaza raport numar aparitii agregare maxima.
        /// </summary>
        public static string TimeReport_Button_GenerateReport_CountReportMaximumAggregation {
            get {
                return ResourceManager.GetString("TimeReport_Button_GenerateReport_CountReportMaximumAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genereaza raport detaliat.
        /// </summary>
        public static string TimeReport_Button_GenerateReport_TimeReportDetails {
            get {
                return ResourceManager.GetString("TimeReport_Button_GenerateReport_TimeReportDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genereaza raport procentual agregat.
        /// </summary>
        public static string TimeReport_Button_GenerateReport_TimeReportFirstAggregation {
            get {
                return ResourceManager.GetString("TimeReport_Button_GenerateReport_TimeReportFirstAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genereaza raport agregare maxima.
        /// </summary>
        public static string TimeReport_Button_GenerateReport_TimeReportMaximumAggregation {
            get {
                return ResourceManager.GetString("TimeReport_Button_GenerateReport_TimeReportMaximumAggregation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alegeti perioada.
        /// </summary>
        public static string TimeReport_ChoosePeriod {
            get {
                return ResourceManager.GetString("TimeReport_ChoosePeriod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data final.
        /// </summary>
        public static string TimeReport_EndTime {
            get {
                return ResourceManager.GetString("TimeReport_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume fisier.
        /// </summary>
        public static string TimeReport_FileName {
            get {
                return ResourceManager.GetString("TimeReport_FileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perioada identificata.
        /// </summary>
        public static string TimeReport_QueryMatchLength {
            get {
                return ResourceManager.GetString("TimeReport_QueryMatchLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodia a fost gasita la.
        /// </summary>
        public static string TimeReport_QueryMatchStartsAt {
            get {
                return ResourceManager.GetString("TimeReport_QueryMatchStartsAt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id rezultat.
        /// </summary>
        public static string TimeReport_ResultId {
            get {
                return ResourceManager.GetString("TimeReport_ResultId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alegeti conturile.
        /// </summary>
        public static string TimeReport_SelectAccounts {
            get {
                return ResourceManager.GetString("TimeReport_SelectAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alegeti posturile.
        /// </summary>
        public static string TimeReport_SelectStreamStations {
            get {
                return ResourceManager.GetString("TimeReport_SelectStreamStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alegeti melodiile.
        /// </summary>
        public static string TimeReport_SelectTracks {
            get {
                return ResourceManager.GetString("TimeReport_SelectTracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data start.
        /// </summary>
        public static string TimeReport_StartTime {
            get {
                return ResourceManager.GetString("TimeReport_StartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id inregistrare.
        /// </summary>
        public static string TimeReport_StreamId {
            get {
                return ResourceManager.GetString("TimeReport_StreamId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id post.
        /// </summary>
        public static string TimeReport_StreamStationId {
            get {
                return ResourceManager.GetString("TimeReport_StreamStationId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume post.
        /// </summary>
        public static string TimeReport_StreamStationName {
            get {
                return ResourceManager.GetString("TimeReport_StreamStationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posturi.
        /// </summary>
        public static string TimeReport_StreamStations {
            get {
                return ResourceManager.GetString("TimeReport_StreamStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timp total.
        /// </summary>
        public static string TimeReport_TotalTimeInSeconds {
            get {
                return ResourceManager.GetString("TimeReport_TotalTimeInSeconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume artist.
        /// </summary>
        public static string TimeReport_TrackArtist {
            get {
                return ResourceManager.GetString("TimeReport_TrackArtist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id melodie.
        /// </summary>
        public static string TimeReport_TrackId {
            get {
                return ResourceManager.GetString("TimeReport_TrackId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durata melodie.
        /// </summary>
        public static string TimeReport_TrackLength {
            get {
                return ResourceManager.GetString("TimeReport_TrackLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodii.
        /// </summary>
        public static string TimeReport_Tracks {
            get {
                return ResourceManager.GetString("TimeReport_Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titlu melodie.
        /// </summary>
        public static string TimeReport_TrackTitle {
            get {
                return ResourceManager.GetString("TimeReport_TrackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume album.
        /// </summary>
        public static string Track_Album {
            get {
                return ResourceManager.GetString("Track_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume artist.
        /// </summary>
        public static string Track_Artist {
            get {
                return ResourceManager.GetString("Track_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id melodie.
        /// </summary>
        public static string Track_Id {
            get {
                return ResourceManager.GetString("Track_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este activa.
        /// </summary>
        public static string Track_IsActive {
            get {
                return ResourceManager.GetString("Track_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este noua.
        /// </summary>
        public static string Track_IsNew {
            get {
                return ResourceManager.GetString("Track_IsNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISRC.
        /// </summary>
        public static string Track_Isrc {
            get {
                return ResourceManager.GetString("Track_Isrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durata melodie.
        /// </summary>
        public static string Track_Length {
            get {
                return ResourceManager.GetString("Track_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An aparitie.
        /// </summary>
        public static string Track_ReleaseYear {
            get {
                return ResourceManager.GetString("Track_ReleaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodia a fost salvata cu succes!.
        /// </summary>
        public static string Track_SuccessfullyCreated {
            get {
                return ResourceManager.GetString("Track_SuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodia a fost modificata cu succes!.
        /// </summary>
        public static string Track_SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("Track_SuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titlu melodie.
        /// </summary>
        public static string Track_Title {
            get {
                return ResourceManager.GetString("Track_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creaza melodie.
        /// </summary>
        public static string Track_Title_CreateTrack {
            get {
                return ResourceManager.GetString("Track_Title_CreateTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica melodie.
        /// </summary>
        public static string Track_Title_EditTrack {
            get {
                return ResourceManager.GetString("Track_Title_EditTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista melodii.
        /// </summary>
        public static string Track_Title_TrackList {
            get {
                return ResourceManager.GetString("Track_Title_TrackList", resourceCulture);
            }
        }
    }
}
