//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume cont.
        /// </summary>
        public static string Account_AccountName {
            get {
                return ResourceManager.GetString("Account_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adresa.
        /// </summary>
        public static string Account_Address {
            get {
                return ResourceManager.GetString("Account_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista melodii.
        /// </summary>
        public static string Account_Button_AccountTrackList {
            get {
                return ResourceManager.GetString("Account_Button_AccountTrackList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Account_Email {
            get {
                return ResourceManager.GetString("Account_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume.
        /// </summary>
        public static string Account_FullName {
            get {
                return ResourceManager.GetString("Account_FullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id cont.
        /// </summary>
        public static string Account_Id {
            get {
                return ResourceManager.GetString("Account_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este activ.
        /// </summary>
        public static string Account_IsActive {
            get {
                return ResourceManager.GetString("Account_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Telefon.
        /// </summary>
        public static string Account_Phone {
            get {
                return ResourceManager.GetString("Account_Phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contul a fost creat cu succes!.
        /// </summary>
        public static string Account_SuccessfullyCreated {
            get {
                return ResourceManager.GetString("Account_SuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contul a fost actualizat cu succes!.
        /// </summary>
        public static string Account_SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("Account_SuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista conturi.
        /// </summary>
        public static string Account_Title_AccountList {
            get {
                return ResourceManager.GetString("Account_Title_AccountList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creeaza cont.
        /// </summary>
        public static string Account_Title_CreateAccount {
            get {
                return ResourceManager.GetString("Account_Title_CreateAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica cont.
        /// </summary>
        public static string Account_Title_EditAccount {
            get {
                return ResourceManager.GetString("Account_Title_EditAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id cont.
        /// </summary>
        public static string ApplicationSetting_AccountId {
            get {
                return ResourceManager.GetString("ApplicationSetting_AccountId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cont.
        /// </summary>
        public static string ApplicationSetting_AccountName {
            get {
                return ResourceManager.GetString("ApplicationSetting_AccountName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriere.
        /// </summary>
        public static string ApplicationSetting_Description {
            get {
                return ResourceManager.GetString("ApplicationSetting_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id setare.
        /// </summary>
        public static string ApplicationSetting_Id {
            get {
                return ResourceManager.GetString("ApplicationSetting_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este activa.
        /// </summary>
        public static string ApplicationSetting_IsActive {
            get {
                return ResourceManager.GetString("ApplicationSetting_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denumire cheie.
        /// </summary>
        public static string ApplicationSetting_KeyName {
            get {
                return ResourceManager.GetString("ApplicationSetting_KeyName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Valoare cheie.
        /// </summary>
        public static string ApplicationSetting_KeyValue {
            get {
                return ResourceManager.GetString("ApplicationSetting_KeyValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setarea a fost creata cu succes!.
        /// </summary>
        public static string ApplicationSetting_SuccessfullyCreated {
            get {
                return ResourceManager.GetString("ApplicationSetting_SuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setarea a fost actualizata cu succes!.
        /// </summary>
        public static string ApplicationSetting_SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("ApplicationSetting_SuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista setari.
        /// </summary>
        public static string ApplicationSetting_Title_ApplicationSettingList {
            get {
                return ResourceManager.GetString("ApplicationSetting_Title_ApplicationSettingList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creeaza setarea.
        /// </summary>
        public static string ApplicationSetting_Title_CreateApplicationSetting {
            get {
                return ResourceManager.GetString("ApplicationSetting_Title_CreateApplicationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica setarea.
        /// </summary>
        public static string ApplicationSetting_Title_EditApplicationSetting {
            get {
                return ResourceManager.GetString("ApplicationSetting_Title_EditApplicationSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back.
        /// </summary>
        public static string Global_Button_Back {
            get {
                return ResourceManager.GetString("Global_Button_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        public static string Global_Button_Create {
            get {
                return ResourceManager.GetString("Global_Button_Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Global_Button_Edit {
            get {
                return ResourceManager.GetString("Global_Button_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Global_Button_Save {
            get {
                return ResourceManager.GetString("Global_Button_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save and continue.
        /// </summary>
        public static string Global_Button_SaveContinue {
            get {
                return ResourceManager.GetString("Global_Button_SaveContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toate.
        /// </summary>
        public static string Global_Lookup_All {
            get {
                return ResourceManager.GetString("Global_Lookup_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.
        /// </summary>
        public static string Global_Lookup_IdZero {
            get {
                return ResourceManager.GetString("Global_Lookup_IdZero", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Conturi.
        /// </summary>
        public static string Global_NavBar_Accounts {
            get {
                return ResourceManager.GetString("Global_NavBar_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setari.
        /// </summary>
        public static string Global_NavBar_ApplicationSettings {
            get {
                return ResourceManager.GetString("Global_NavBar_ApplicationSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alocare posturi per cont.
        /// </summary>
        public static string Global_NavBar_StationAccountAllocation {
            get {
                return ResourceManager.GetString("Global_NavBar_StationAccountAllocation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Posturi.
        /// </summary>
        public static string Global_NavBar_StreamStations {
            get {
                return ResourceManager.GetString("Global_NavBar_StreamStations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodii.
        /// </summary>
        public static string Global_NavBar_Tracks {
            get {
                return ResourceManager.GetString("Global_NavBar_Tracks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Descriere.
        /// </summary>
        public static string StreamStation_Description {
            get {
                return ResourceManager.GetString("StreamStation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id post.
        /// </summary>
        public static string StreamStation_Id {
            get {
                return ResourceManager.GetString("StreamStation_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este activa.
        /// </summary>
        public static string StreamStation_IsActive {
            get {
                return ResourceManager.GetString("StreamStation_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necesara conversie.
        /// </summary>
        public static string StreamStation_IsConvertionNeeded {
            get {
                return ResourceManager.GetString("StreamStation_IsConvertionNeeded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorul local.
        /// </summary>
        public static string StreamStation_LocalPath {
            get {
                return ResourceManager.GetString("StreamStation_LocalPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Functioneaza.
        /// </summary>
        public static string StreamStation_Running {
            get {
                return ResourceManager.GetString("StreamStation_Running", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Denumire post.
        /// </summary>
        public static string StreamStation_StationName {
            get {
                return ResourceManager.GetString("StreamStation_StationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postul a fost creat cu succes!.
        /// </summary>
        public static string StreamStation_SuccessfullyCreated {
            get {
                return ResourceManager.GetString("StreamStation_SuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postul a fost actualizat cu succes!.
        /// </summary>
        public static string StreamStation_SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("StreamStation_SuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creaza post.
        /// </summary>
        public static string StreamStation_Title_CreateStreamStation {
            get {
                return ResourceManager.GetString("StreamStation_Title_CreateStreamStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica post.
        /// </summary>
        public static string StreamStation_Title_EditStreamStation {
            get {
                return ResourceManager.GetString("StreamStation_Title_EditStreamStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista posturi.
        /// </summary>
        public static string StreamStation_Title_StreamStationList {
            get {
                return ResourceManager.GetString("StreamStation_Title_StreamStationList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directorul unde se face transformarea.
        /// </summary>
        public static string StreamStation_TransformFolder {
            get {
                return ResourceManager.GetString("StreamStation_TransformFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL.
        /// </summary>
        public static string StreamStation_Url {
            get {
                return ResourceManager.GetString("StreamStation_Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume album.
        /// </summary>
        public static string Track_Album {
            get {
                return ResourceManager.GetString("Track_Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nume artist.
        /// </summary>
        public static string Track_Artist {
            get {
                return ResourceManager.GetString("Track_Artist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Id melodie.
        /// </summary>
        public static string Track_Id {
            get {
                return ResourceManager.GetString("Track_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Este activa.
        /// </summary>
        public static string Track_IsActive {
            get {
                return ResourceManager.GetString("Track_IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ISRC.
        /// </summary>
        public static string Track_Isrc {
            get {
                return ResourceManager.GetString("Track_Isrc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Durata melodie.
        /// </summary>
        public static string Track_Length {
            get {
                return ResourceManager.GetString("Track_Length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An aparitie.
        /// </summary>
        public static string Track_ReleaseYear {
            get {
                return ResourceManager.GetString("Track_ReleaseYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodia a fost salvata cu succes!.
        /// </summary>
        public static string Track_SuccessfullyCreated {
            get {
                return ResourceManager.GetString("Track_SuccessfullyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Melodia a fost modificata cu succes!.
        /// </summary>
        public static string Track_SuccessfullyUpdated {
            get {
                return ResourceManager.GetString("Track_SuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titlu melodie.
        /// </summary>
        public static string Track_Title {
            get {
                return ResourceManager.GetString("Track_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creaza melodie.
        /// </summary>
        public static string Track_Title_CreateTrack {
            get {
                return ResourceManager.GetString("Track_Title_CreateTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifica melodie.
        /// </summary>
        public static string Track_Title_EditTrack {
            get {
                return ResourceManager.GetString("Track_Title_EditTrack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista melodii.
        /// </summary>
        public static string Track_Title_TrackList {
            get {
                return ResourceManager.GetString("Track_Title_TrackList", resourceCulture);
            }
        }
    }
}
