// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicIdentificationSystem.EF.Entities
{

    // ApplicationSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class ApplicationSettingEntity
    {
        public int Id { get; set; } // Id (Primary key)
        public string KeyName { get; set; } // KeyName (length: 250)
        public string KeyValue { get; set; } // KeyValue (length: 250)

        public ApplicationSettingEntity()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
