// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicIdentificationSystem.EF.Entities
{

    // Results
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class ResultEntity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? StreamId { get; set; } // StreamId
        public int? TrackId { get; set; } // TrackId
        public string Filename { get; set; } // filename (length: 250)
        public decimal? MatchStartAt { get; set; } // MatchStartAt

        // Foreign keys

        /// <summary>
        /// Parent Stream pointed by [Results].([StreamId]) (FK_TrackResults_Stream)
        /// </summary>
        public virtual StreamEntity Stream { get; set; } // FK_TrackResults_Stream

        /// <summary>
        /// Parent Track pointed by [Results].([TrackId]) (FK_TrackResults_Tracks)
        /// </summary>
        public virtual TrackEntity Track { get; set; } // FK_TrackResults_Tracks

        public ResultEntity()
        {
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
