// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicIdentificationSystem.EF.Entities
{

    // Stream
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class StreamEntity
    {
        public int Id { get; set; } // Id (Primary key)
        public int? StationId { get; set; } // StationId
        public System.DateTime? StartTime { get; set; } // StartTime
        public System.DateTime? EndTime { get; set; } // EndTime
        public string FileName { get; set; } // FileName (length: 250)

        // Reverse navigation

        /// <summary>
        /// Child Results where [Results].[StreamId] point to this entity (FK_TrackResults_Stream)
        /// </summary>
        public virtual System.Collections.Generic.ICollection<ResultEntity> Results { get; set; } // Results.FK_TrackResults_Stream

        // Foreign keys

        /// <summary>
        /// Parent StreamStation pointed by [Stream].([StationId]) (FK_Stream_StreamStations)
        /// </summary>
        public virtual StreamStationEntity StreamStation { get; set; } // FK_Stream_StreamStations

        public StreamEntity()
        {
            Results = new System.Collections.Generic.List<ResultEntity>();
            InitializePartial();
        }

        partial void InitializePartial();
    }

}
// </auto-generated>
