// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicIdentificationSystem.EF.Mappings
{
    using MusicIdentificationSystem.EF.Context;
    using MusicIdentificationSystem.EF.Entities;

    // ApplicationSettings
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class ApplicationSettingEntityMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<ApplicationSettingEntity>
    {
        public ApplicationSettingEntityMapping()
            : this("dbo")
        {
        }

        public ApplicationSettingEntityMapping(string schema)
        {
            ToTable("ApplicationSettings", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.KeyName).HasColumnName(@"KeyName").HasColumnType("nvarchar").IsOptional().HasMaxLength(250);
            Property(x => x.KeyValue).HasColumnName(@"KeyValue").HasColumnType("nvarchar").IsOptional().HasMaxLength(250);
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
