// <auto-generated>
// ReSharper disable ConvertPropertyToExpressionBody
// ReSharper disable DoNotCallOverridableMethodsInConstructor
// ReSharper disable InconsistentNaming
// ReSharper disable PartialMethodWithSinglePart
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable RedundantOverridenMember
// ReSharper disable UseNameofExpression
// TargetFrameworkVersion = 4.6
#pragma warning disable 1591    //  Ignore "Missing XML Comment" warning


namespace MusicIdentificationSystem.EF.Mappings
{
    using MusicIdentificationSystem.EF.Context;
    using MusicIdentificationSystem.EF.Entities;

    // Stream
    [System.CodeDom.Compiler.GeneratedCode("EF.Reverse.POCO.Generator", "2.32.0.0")]
    public partial class StreamEntityMapping : System.Data.Entity.ModelConfiguration.EntityTypeConfiguration<StreamEntity>
    {
        public StreamEntityMapping()
            : this("dbo")
        {
        }

        public StreamEntityMapping(string schema)
        {
            ToTable("Stream", schema);
            HasKey(x => x.Id);

            Property(x => x.Id).HasColumnName(@"Id").HasColumnType("int").IsRequired().HasDatabaseGeneratedOption(System.ComponentModel.DataAnnotations.Schema.DatabaseGeneratedOption.Identity);
            Property(x => x.StationId).HasColumnName(@"StationId").HasColumnType("int").IsOptional();
            Property(x => x.StartTime).HasColumnName(@"StartTime").HasColumnType("datetime").IsOptional();
            Property(x => x.EndTime).HasColumnName(@"EndTime").HasColumnType("datetime").IsOptional();
            Property(x => x.FileName).HasColumnName(@"FileName").HasColumnType("nvarchar").IsOptional().HasMaxLength(250);

            // Foreign keys
            HasOptional(a => a.StreamStation).WithMany(b => b.Streams).HasForeignKey(c => c.StationId).WillCascadeOnDelete(false); // FK_Stream_StreamStations
            InitializePartial();
        }
        partial void InitializePartial();
    }

}
// </auto-generated>
